'''
General things to consider
'''

'''
IDEA:

a character has moves
there are multiple characters
characters react to program command
program commands are generated by program states
program states reacts to button input
players provide button input
ergo player controls character's moves

'''

health = True
style = True
speed = True # Distance
stun = True
jump = True

'''
GOAL:
to be able to at-a-glance see and compare fighters to see which one to pick or explore

'''
